Areas/Admin/Controllers/HotelServicesController.cs
using AutoMapper;
using Hotel_Management.Areas.Admin.Services;
using Hotel_Management.Areas.Admin.Services.Interfaces;
using Hotel_Management.Areas.Admin.ViewModels;
using Hotel_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Staff")]
    public class HotelServicesController : Controller
    {
        private readonly IHotelSServices _hotelSServices;
        private readonly IMapper _mapper;

        public HotelServicesController(IHotelSServices hotelSServices, IMapper mapper)
        {
            _hotelSServices = hotelSServices;
            _mapper = mapper;
        }

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;
        [BindProperty(SupportsGet = true)]
        public string? QuerySearch { get; set; } = string.Empty;

        // [GET] /Admin/HotelServices
        public async Task<IActionResult> Index()
        {
            var services = await _hotelSServices.GetAllAsync(QuerySearch, PageIndex);

            ViewBag.QuerySearch = QuerySearch;

            return View(services);
        }

        // [GET] /Admin/HotelServices/Detail/{id}
        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            try
            {
                var service = await _hotelSServices.GetByIdAsync(id);
                return View(service);
            }
            catch (ArgumentNullException ex)
            {
                // Log the exception (ex) if necessary
                return NotFound(ex.Message);
            }
            catch (InvalidOperationException ex)
            {
                // Log the exception (ex) if necessary
                return BadRequest(ex.Message);
            }
        }

        // [GET] /Admin/HotelServices/Create
        public IActionResult Create()
        {
            return View();
        }

        // [POST] /Admin/HotelServices/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HotelServicesVM model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var service = _mapper.Map<Service>(model);
                    await _hotelSServices.CreateAsync(service);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(model);
        }

        // [GET] /Admin/HotelServices/Edit/{id}
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            var service = await _hotelSServices.GetByIdAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<HotelServicesVM>(service);
            return View(model);
        }

        // [POST] /Admin/HotelServices/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, HotelServicesVM model)
        {
            if (id <= 0 || id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var service = _mapper.Map<Service>(model);
                    await _hotelSServices.UpdateAsync(service);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(model);
        }

        // [POST] /Admin/HotelServices/Delete/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            try
            {
                await _hotelSServices.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View("Index", await _hotelSServices.GetAllAsync(QuerySearch, PageIndex));
            }
        }
    }
}

Pages/Reviews/Edit.cshtml.cs
using System.Security.Claims;
using AutoMapper;
using Hotel_Management.Areas.Admin.ViewModels;
using Hotel_Management.Models;
using Hotel_Management.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel_Management.Pages.Reviews
{
    public class EditModel : PageModel
    {
        private readonly IReviewsService _reviewsService;
        private readonly IMapper _mapper;

        public EditModel(IReviewsService reviewsService, IMapper mapper)
        {
            _reviewsService = reviewsService;
            _mapper = mapper;
        }

        [BindProperty]
        public ReviewVM Review { get; set; } = new ReviewVM();
        [BindProperty(SupportsGet = true)]
        public int ReviewId { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                var review = await _reviewsService.GetByIdAsync(ReviewId, User.FindFirstValue(ClaimTypes.NameIdentifier));
                if (review != null)
                {
                    Review = _mapper.Map<ReviewVM>(review);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Review not found.");
                }

                return Page();
            }
            catch (Exception ex)
            {
                return NotFound($"An error occurred while retrieving the review: {ex.Message}");
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                var review = _mapper.Map<Review>(Review);
                var result = await _reviewsService.UpdateAsync(review, User.FindFirstValue(ClaimTypes.NameIdentifier));
                if (result)
                {
                    return RedirectToPage("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Failed to update the review.");
                    return Page();
                }
            }
            catch (Exception ex)
            {
                return BadRequest($"An error occurred while updating the review: {ex.Message}");
            }
        }
    }
}

Pages/Rooms/Detail.cshtml.cs
using Hotel_Management.Extensions;
using Hotel_Management.Models;
using Hotel_Management.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel_Management.Rooms.Pages
{
    public class DetailModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IRoomsService _roomsService;

        public DetailModel(SignInManager<ApplicationUser> signInManager,IRoomsService roomsService)
        {
            _signInManager = signInManager;
            _roomsService = roomsService;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public Room room { get; set; } = new Room();
        public List<Roomimage> Roomimage { get; set; } = new List<Roomimage>();

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Console.WriteLine("Fetching room details for ID: " + Id);
                room = await _roomsService.GetRoomByIdAsync(Id);
                if (room == null)
                {
                    ModelState.AddModelError(string.Empty, "Room not found.");
                }

                if (room.Roomimages != null && room.Roomimages.Count > 0)
                {
                    Roomimage = room.Roomimages.ToList();
                }

                return Page();
            }
            catch (Exception ex)
            {
                // Handle exceptions (e.g., log the error, show an error message)
                ModelState.AddModelError(string.Empty, "An error occurred while retrieving the room: " + ex.Message);
                return Page();
            }
        }

        public async Task<IActionResult> OnPostAddWishListAsync(
            int RoomId,
            string? RoomNumber,
            string? RoomType,
            string? RoomImage,
            decimal Price,
            DateOnly CheckInDate,
            DateOnly CheckOutDate,
            String Status = "Available"
        )
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToPage(
                    "/Account/Login",
                    new { area = "Identity", returnUrl = Url.Page("/Rooms/Detail", new { id = RoomId }) }
                );
            }

            if (Status == "Occupied")
            {
                TempData["ErrorMessage"] = "Phòng này hiện đang được sử dụng. Vui lòng chọn phòng khác.";
                return RedirectToPage("/Rooms/Detail", new { id = RoomId });
            }

            if (CheckInDate >= CheckOutDate)
            {
                TempData["ErrorMessage"] = "Ngày nhận phòng phải nhỏ hơn ngày trả phòng.";
                return RedirectToPage("/Rooms/Detail", new { id = RoomId });
            }

            if (CheckInDate < DateOnly.FromDateTime(DateTime.Now))
            {
                TempData["ErrorMessage"] = "Ngày nhận phòng phải lớn hơn hoặc bằng ngày hiện tại.";
                return RedirectToPage("/Rooms/Detail", new { id = RoomId });
            }

            if (CheckOutDate < DateOnly.FromDateTime(DateTime.Now))
            {
                TempData["ErrorMessage"] = "Ngày trả phòng phải lớn hơn hoặc bằng ngày hiện tại.";
                return RedirectToPage("/Rooms/Detail", new { id = RoomId });
            }

            var room = await _roomsService.GetRoomByIdAsync(RoomId);

            if (room == null)
            {
                return NotFound("Room not found.");
            }

            var wishList = HttpContext.Session.GetObject<List<BookingItem>>("wishlist") ?? new List<BookingItem>();

            if (wishList.Count == 5)
            {
                TempData["ErrorMessage"] = "Bạn chỉ có thể thêm tối đa 5 phòng vào danh sách yêu thích.";
                return RedirectToPage("/Rooms/Detail", new { id = RoomId });
            }

            wishList.Add(new BookingItem
            {
                RoomId = RoomId,
                RoomNumber = RoomNumber,
                RoomType = RoomType,
                RoomImage = RoomImage,
                Price = Price,
                CheckInDate = CheckInDate,
                CheckOutDate = CheckOutDate
            });

            HttpContext.Session.SetObject("wishlist", wishList);

            return RedirectToPage("/Bookings/WishList");
        }
    }
}

Areas/Admin/Views/HotelServices/Create.cshtml
@using Hotel_Management.Areas.Admin.Services.Interfaces
@using Hotel_Management.Areas.Admin.ViewModels;
@inject IHotelServices hotelServices;
@model HotelServicesVM
@{
    ViewData["Title"] = "Thêm dịch vụ khách sạn";

    var hotels = hotelServices.GetAllAsync().Result;
}

<div class="container mt-5">
    <div class="card shadow rounded-4 border-0">
        <div class="card-header bg-success text-white rounded-top-4">
            <h3 class="mb-0">Thêm dịch vụ mới</h3>
        </div>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
        <div class="card-body mt-2">
            <form asp-area="Admin" asp-controller="HotelServices" asp-action="Create" method="post">
                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <select asp-for="HotelId" class="form-select">
                        <option value="">-- Chọn khách sạn --</option>
                        @foreach (var hotel in hotels)
                        {
                            <option value="@hotel.Id">@hotel.Name</option>
                        }
					</select>
                </div>

                <div class="mb-3">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between">
                    <a asp-action="Index" class="btn btn-secondary">
                        <i class="bi bi-arrow-left"></i> Hủy
                    </a>
                    <button type="submit" class="btn btn-success">
                        <i class="bi bi-plus-circle"></i> Thêm dịch vụ
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/HotelServices/Detail.cshtml
@using Hotel_Management.Models
@model Service
@{
    ViewData["Title"] = "Chi tiết dịch vụ";
}

<div class="container mt-5">
    <div class="card shadow rounded-4 border-0">
        <div class="card-header bg-primary text-white rounded-top-4">
            <h3 class="mb-0">Thông tin dịch vụ</h3>
        </div>
        <div class="card-body mt-2">
            <dl class="row">
                <dt class="col-sm-3">ID</dt>
                <dd class="col-sm-9">@Model.Id</dd>

                <dt class="col-sm-3">Tên dịch vụ</dt>
                <dd class="col-sm-9">@Model.Name</dd>

                <dt class="col-sm-3">Mô tả</dt>
                <dd class="col-sm-9">@Model.Description</dd>

                <dt class="col-sm-3">Price</dt>
                <dd class="col-sm-9">@String.Format("{0:N0} VNĐ", Model.Price)</dd>

                <dt class="col-sm-3">Dịch vụ của khách sạn</dt>
                <dd class="col-sm-9">@Model.Hotel.Name</dd>
            </dl>
        </div>
        <div class="card-footer text-end">
            <a asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Quay lại danh sách
            </a>
        </div>
    </div>
</div>

Areas/Admin/Views/HotelServices/Edit.cshtml
@using Hotel_Management.Areas.Admin.ViewModels;
@using Hotel_Management.Areas.Admin.Services.Interfaces
@inject IHotelServices hotelServices;
@model HotelServicesVM
@{
    ViewData["Title"] = "Sửa thông tin dịch vụ";

    var hotels = hotelServices.GetAllAsync().Result;
}

<div class="container mt-5">
    <div class="card shadow rounded-4 border-0">
        <div class="card-header bg-success text-white rounded-top-4">
            <h3 class="mb-0">Sửa thông tin dịch vụ</h3>
        </div>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
        <div class="card-body mt-2">
            <form asp-area="Admin" asp-controller="HotelServices" asp-action="Edit" method="post">
				<input type="hidden" asp-for="Id" />
                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Description" class="form-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <select asp-for="HotelId" class="form-select">
                        <option value="">-- Chọn khách sạn --</option>
                        @foreach (var hotel in hotels)
                        {
                            <option value="@hotel.Id">@hotel.Name</option>
                        }
                    </select>
                </div>

                <div class="mb-3">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="d-flex justify-content-between">
                    <a asp-action="Index" class="btn btn-secondary">
                        <i class="bi bi-arrow-left"></i> Hủy
                    </a>
                    <button type="submit" class="btn btn-success">
                        <i class="bi bi-plus-circle"></i> Sửa dịch vụ
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Areas/Admin/Views/HotelServices/Index.cshtml
@using Hotel_Management.Helpers
@using Hotel_Management.Models
@model PaginatedList<Service>
@{
    ViewData["Title"] = "Danh sách dịch vụ khách sạn";
}

<div class="row">
    <div class="col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Danh sách dịch vụ</div>
                <div class="search-container">
                    <!-- Search input group start -->
                    <form asp-area="Admin" asp-controller="HotelServices" asp-action="Index" method="get" class="input-group">
                        <input type="text" class="form-control" style="border: 1px solid black;" name="QuerySearch"
                               placeholder="Tìm kiếm dịch vụ">
                        <button class="btn" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </form>
                    <!-- Search input group end -->
                </div>
                <a asp-area="Admin" asp-controller="HotelServices" asp-action="Index" class="btn btn-danger">
                    Xóa tìm kiếm
                </a>

                <a asp-area="Admin" asp-controller="HotelServices" asp-action="Create" class="btn btn-primary ms-1">
                    <i class="bi bi-plus"></i>
                    Thêm dịch vụ
                </a>
            </div>
            <div class="card-body">
                @if (Model.Count == 0)
                {
                    <div class="alert alert-info" role="alert">
                        Không có dịch vụ nào được tìm thấy.
                    </div>
                }
                else
                {
                    <div class="table-responsive">
                        <table class="table v-middle m-0">
                            <thead>
                                <tr>
                                    <th>Tên dịch vụ</th>
                                    <th>Mô tả</th>
                                    <th>Price</th>
                                    <th>Khách sạn</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var service in Model)
                                {
                                    <tr>
                                        <td>@service.Name</td>
                                        <td>@service.Description</td>
                                        <td>@String.Format("{0:N0} VNĐ", service.Price)</td>
                                        <td>@service.Hotel.Name</td>
                                        <td>
                                            <div class="actions">
                                                <a asp-area="Admin" asp-controller="HotelServices" asp-action="Detail" asp-route-id="@service.Id" class="viewRow">
                                                    <i class="bi bi-list text-green"></i>
                                                </a>
                                                <a asp-area="Admin" asp-controller="HotelServices" asp-action="Edit" asp-route-id="@service.Id" class="viewRow">
                                                    <i class="bi bi-pencil text-yellow"></i>
                                                </a>
                                                <a href="#" class="deleteRow" data-id="@service.Id">
                                                    <i class="bi bi-trash text-red"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <br />

                        <!-- Phân trang -->
                        <nav aria-label="Page Navigation">
                            <ul class="pagination justify-content-end">
                                <li class="page-item">
                                    @if (Model.HasPreviousPage)
                                    {
                                        <a class="page-link" href="@Url.Action("Index", new { PageIndex = Model.PageIndex - 1, QuerySearch = ViewBag.QuerySearch  })"
                                           aria-label="Previous">
                                            <span aria-hidden="true">
                                                <i class="bi bi-arrow-left"></i>
                                            </span>
                                        </a>
                                    }
                                </li>
                                @for (int i = 1; i <= Model.TotalPages; i++)
                                {
                                    <li class="page-item @(Model.PageIndex == i ? "active" : "")">
                                        <a class="page-link" href="@Url.Action("Index", new { PageIndex = i, QuerySearch = ViewBag.QuerySearch  })">@i</a>
                                    </li>
                                }
                                <li class="page-item">
                                    @if (Model.HasNextPage)
                                    {
										<a class="page-link" href="@Url.Action("Index", new { PageIndex = Model.PageIndex + 1, QuerySearch = ViewBag.QuerySearch })"
                                           aria-label="Next">
                                            <span aria-hidden="true">
                                                <i class="bi bi-arrow-right"></i>
                                            </span>
                                        </a>
                                    }
                                </li>
                            </ul>
                        </nav>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<form asp-area="Admin" asp-controller="HotelServices" asp-action="Delete" method="post" name="delete">
    <input type="hidden" name="id" />
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const deleteButtons = document.querySelectorAll(".deleteRow");
        deleteButtons.forEach(button => {
            button.addEventListener("click", function (event) {
                event.preventDefault();
                const customerId = this.getAttribute("data-id");
                const form = document.forms["delete"];
                form.querySelector("input[name='id']").value = customerId;

                if (confirm("Bạn có chắc chắn muốn xóa dịch vụ này?")) {
                    form.submit();
                }
            });
        });
    });
</script>